### PR TITLE
Discord

### PR DESCRIPTION
**Pull request by Apexal**
**Changes in this pull request**:
- Switch references to Discord
- Add Discord info

Still needed:
- page about the server categories, automation, etc.

### CODE REVIEW

**Comment by OliviaLundelius** [comment]
Should we retain a note somewhere about continuing support for Mattermost for students currently remote and in China or other locations where Discord is banned?

**Comment by Apexal** [comment]
Maintaining Mattermost was extremely difficult at the start of the semester, and it appears that it is not used any longer. Adrian mentioned a few weeks ago that only one message had been sent in the Mattermost in the past month, and the few people I had spoken to on the Mattermost simply preferred it over Discord and did not have a problem switching. I personally think it is worth dropping support for Mattermost unless students express concern at the start of each semester. Opinions?

**Comment by Apexal** [comment]
I'll add a Mattermost section for now though so we can merge.

**Comment by Apexal** [comment]
Adrian is shutting down the Mattermost so we are going forward with this!

**Pull request merged**
